module.exports = {
  title: "UCB `README.md` Generator",
  description: "A command-line application that dynamically generates a professional `README.md` file from a user's input using the Inquirer package.",
  confirmTOC: true,
  deployment: "This app is not deployed online. It runs on `Node.js` in your command-line interface (CLI)",
  repo: "This app is not deployed online. It runs on `Node.js` in your command-line interface (CLI).",
  installationFirst: "Clone the app to your local machine. This will copy `package.json` to your local machine, which includes the required packages (modules/dependencies).",
  installationMore: "Run `npm install`. This will automatically install the dependecies, which in this case is `inquirer`.",
  usage: "Go to the command line, such as Terminal, Vim, etc.",
  confirmScreenshot: true,
  screenshot: "screenshot.png",
  confirmVideo: false,
  tech: "Inquirer",
  confirmCollaborators: false,
  confirmLicense: true,
  license: 'GNU GPL v3',
  features: "This is a simple Command-Line Iinterface (CLI) app that uses the `inquirer` module to ask the user a series of questions. The answers are used to automatically generate a `README.md` file in the same directory/folder where the app is run.",
  confirmContributing: false,
  confirmTests: false,
  confirmRoadmap: true,
  name: "Ahmad El Gamal",
  username: "ahmadelgamal",
  email: "ahmadelgamal@gmail.com"
};