module.exports = {
  title: "UCB `README.md` Generator",
  description: "A command-line application that dynamically generates a professional `README.md` file from a user's input using the Inquirer package.",
  confirmTOC: true,
  deployment: "This is a command-line application. It is not deployed online.",
  repo: "https://github.com/ahmadelgamal/ucb-README-generator",
  installationFirst: "Clone the app to your local machine. This will copy `package.json` to your local machine, which includes the required packages (modules/dependencies).",
  installationMore: "Run `npm install`. This will automatically install the dependecies, which in this case is `inquirer`.",
  usage: "Go to the command line.",
  confirmScreenshot: true,
  screenshot: "screenshot.png",
  confirmVideo: false,
  tech: "Inquirer.js",
  confirmCollaborators: false,
  confirmLicense: true,
  license: 'MIT',
  features: "This is a simple Command-Line Iinterface (CLI) app that uses the `inquirer` module to ask the user a series of questions. The answers are used to automatically generate a `README.md` file in the same directory/folder where the app is run.",
  confirmContributing: false,
  confirmTests: true,
  tests: "Run the command `npm test` to generate a sample `README.md`. You can change the test values by changing the values of the object in the `sample-answers.js` file, located in the `__test` folder.",
  confirmRoadmap: true,
  roadmap: "1. Add more license options. 1. Add support for more badges. 1. Add autocomplete. 1. Add trim() to user input.",
  name: "Ahmad El Gamal.",
  username: "ahmadelgamal",
  email: "ahmadelgamal@gmail.com"
};