module.exports = {
  title: "README Gen Pro",
  description: "README Gen Pro is a command-line application that dynamically generates a professional `README.md` file from a user's input using the `inquirer.js` package.",
  confirmTOC: true,
  deployment: "This is a command-line application. It is not deployed online.",
  repo: "https://github.com/ahmadelgamal/README-Gen-Pro",
  features: "This is an easy to use Command-Line application. | It uses the `inquirer` module to ask the user a series of questions. | The answers are used to automatically generate a `README.md` file in an `output` directory/folder.",
  installation: "Clone this repository. | Install modules: `npm install`.",
  usage: "Go to the command line. | Run `node index.js` (or `npm start`). | Answer the question prompts. | Once completed, check the `output` folder for the `README.md` file. | If you chose to add a gif animation/screenshot file, then either add it to a `./assets/images` folder in your app, or change the relative path in the `README.md` file. | If you chose to add a video demo, then either add it to a `./assets/videos` folder in your app, or change the relative path in the `README.md` file.",
  confirmScreenshot: true,
  screenshot: "output.gif",
  confirmVideo: true,
  video: "input.gif",
  tech: "JavaScript | Node.js | Inquirer.js | Markdown",
  confirmCollaborators: false,
  confirmContributing: false,
  confirmTests: true,
  tests: "Run the command `npm test` to generate a sample `README.md`. | You can change the test values by changing the values of the object in the `sample-answers.js` file, located in the `__test` folder.",
  confirmRoadmap: true,
  roadmap: "Add more license options. | Add support for more badges. | Add autocomplete. | Add trim() to user input.",
  name: "Ahmad El Gamal",
  username: "ahmadelgamal",
  email: "ahmadelgamal@gmail.com",
  confirmLicense: true,
  license: 'MIT',
  listType: 'Numbers'
};