module.exports = {
  title: "README Gen Pro",
  description: "README Gen Pro is a command-line application that dynamically generates a professional `README.md` file from a user's input using the `inquirer.js` package. (This `README.md` file was generated using this app!)",
  confirmTOC: true,
  deployment: "This is a command-line application. It is not deployed online.",
  repo: "https://github.com/ahmadelgamal/README-Gen-Pro",
  features: "This is an easy to use command-line application. | It uses the `inquirer` module to ask the user a series of questions. | The answers are used to automatically generate a `README.md` file in an `output` directory.",
  confirmPreReq: true,
  preReq: "Install `node.js`.",
  installation: "Download or Clone this repository. | If you downloaded the zipped version of this repo, then unzip it in the desired directory. | Go to the command line (if you're not there already). | Change the directory to `README-Gen-Pro-main` (or `README-Gen-Pro` depending on the name of the installed directory). | Run: `npm install` to install the `inquirer` module.",
  usage: "Go to the command line. | Navigate to the app directory. | Run `node index.js` (or `npm start`). | Answer the question prompts. | Once completed, check the `output` folder for the `README.md` file. | If you chose to add a `gif` animation or `png` screenshot file, then either add it to a `./assets/images` folder in your app, or change the relative path in the `README.md` file to point to the corresponding folder.",
  confirmScreenshot: true,
  screenshot: "screenshot.gif",
  confirmVideo: true,
  video: "https://youtu.be/rEZoblXSlMg",
  tech: "JavaScript | Node.js | Inquirer.js | Markdown",
  confirmCollaborators: false,
  collaborators: "",
  confirmContributing: false,
  contributing: "",
  confirmTests: true,
  tests: "Run the command `npm test` to generate a sample `README.md` from sample answers saved in the object in the `sample-answers.js` file in the `__test__` directory. | You can change the generated `README.md` values by changing the values of the object in the `sample-answers.js` file.",
  confirmRoadmap: true,
  roadmap: "Add more license options. | Add autocomplete. | Add `trim()` to user input.",
  name: "Ahmad El Gamal",
  username: "ahmadelgamal",
  email: "ahmadelgamal@gmail.com",
  confirmLicense: true,
  license: 'MIT',
  listType: 'Numbers'
};